Repository 5hseok/DODAL_BE_SERVER, pull requests merged in 2025-02, with the labels that each got.

#2 [FEAT] Environment 암호화
  .idea/.name
  .idea/gradle.xml
  build.gradle
  src/main/java/ac/dnd/dodal/config/JasyptConfig.java
  src/main/resources/application.yml
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ! MEDIUM, Type 🛠 FEATURE

#3 [REFACTOR] Rename Main -> DodalApplication
  src/main/java/ac/dnd/Main.java
  src/main/java/ac/dnd/dodal/DodalApplication.java
Labels: PR 🚀 WILL CLOSE, Priority ? Low, Type 🔨 REFACTOR

#4 [FEAT] Common + sample API
  build.gradle
  src/main/java/ac/dnd/Main.java
  src/main/java/ac/dnd/dodal/DodalApplication.java
  src/main/java/ac/dnd/dodal/application/goal/repository/.gitkeep
  src/main/java/ac/dnd/dodal/application/goal/service/.gitkeep
  src/main/java/ac/dnd/dodal/application/goal/usecase/.gitkeep
  src/main/java/ac/dnd/dodal/common/enums/CommonResultCode.java
  src/main/java/ac/dnd/dodal/common/enums/ResultCode.java
  src/main/java/ac/dnd/dodal/common/exception/BadRequestException.java
  src/main/java/ac/dnd/dodal/common/exception/DodalControllerAdvice.java
  src/main/java/ac/dnd/dodal/common/exception/DodalException.java
  src/main/java/ac/dnd/dodal/common/exception/ForbiddenException.java
  src/main/java/ac/dnd/dodal/common/exception/InternalServerErrorException.java
  src/main/java/ac/dnd/dodal/common/exception/NotFoundException.java
  src/main/java/ac/dnd/dodal/common/exception/UnauthorizedException.java
  src/main/java/ac/dnd/dodal/common/model/BaseEntity.java
  src/main/java/ac/dnd/dodal/common/response/ApiResponse.java
  src/main/java/ac/dnd/dodal/domain/goal/.gitkeep
  src/main/java/ac/dnd/dodal/domain/goal/enums/.gitkeep
  src/main/java/ac/dnd/dodal/domain/goal/exception/.gitkeep
  src/main/java/ac/dnd/dodal/infrastucture/.gitkeep
  src/main/java/ac/dnd/dodal/ui/goal/.gitkeep
  src/main/java/ac/dnd/dodal/ui/goal/request/.gitkeep
  src/main/java/ac/dnd/dodal/ui/goal/response/.gitkeep
  src/main/java/ac/dnd/dodal/ui/hello/HelloController.java
  src/test/java/ac/dnd/dodal/acceptance/hello/HelloAcceptanceTest.java
  src/test/resources/applicaton-test.yml
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority !! HIGH, Type 🛠 FEATURE

#5 [FIX] Jacoco & Sonar
  .github/workflows/ForkRepoCI.yml
  build.gradle
Labels: PR 🚀 WILL CLOSE, Priority ! MEDIUM, Type 🪰 BUG FIX

#6 [FEAT] Applying DB migration tool (flyway) with DDL
  .github/workflows/ForkRepoCI.yml
  Dockerfile
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__set_feedback.sql
  src/main/resources/db/migration/temp.sql
  src/test/java/ac/dnd/dodal/AcceptanceTest.java
  src/test/java/ac/dnd/dodal/IntegrationTest.java
  src/test/java/ac/dnd/dodal/acceptance/hello/HelloAcceptanceTest.java
  src/test/java/ac/dnd/dodal/config/JasyptConfigTest.java
  src/test/java/ac/dnd/dodal/flyway/FlywayTest.java
  src/test/resources/application-test.yml
  src/test/resources/applicaton-test.yml
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ! MEDIUM, Type 🛠 FEATURE

#14 [REFACTOR] Base Entity
  src/main/java/ac/dnd/dodal/common/model/BaseEntity.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority !! HIGH, Type 🔨 REFACTOR

#17 [FEAT] Goal Command AcceptanceTest
  .github/workflows/ForkRepoCI.yml
  build.gradle
  src/main/java/ac/dnd/dodal/common/model/BaseEntity.java
  src/main/java/ac/dnd/dodal/domain/goal/.gitkeep
  src/main/java/ac/dnd/dodal/domain/goal/constraint/GoalConstraint.java
  src/main/java/ac/dnd/dodal/domain/goal/enums/.gitkeep
  src/main/java/ac/dnd/dodal/domain/goal/exception/.gitkeep
  src/main/java/ac/dnd/dodal/domain/goal/exception/GoalExceptionCode.java
  src/main/java/ac/dnd/dodal/domain/goal/model/Goal.java
  src/main/java/ac/dnd/dodal/ui/goal/request/.gitkeep
  src/main/java/ac/dnd/dodal/ui/goal/request/GoalCreateRequest.java
  src/test/java/ac/dnd/dodal/AcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/goal/AchieveGoalAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/goal/CreateGoalAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/goal/DeleteGoalAcceptanceTets.java
  src/test/java/ac/dnd/dodal/acceptance/goal/steps/GoalSteps.java
  src/test/java/ac/dnd/dodal/acceptance/hello/HelloAcceptanceTest.java
  src/test/java/ac/dnd/dodal/ui/fixture/UIFixture.java
  src/test/java/ac/dnd/dodal/ui/goal/fixture/GoalUIFixture.java
  src/test/resources/application-test.yml
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ! MEDIUM, Type 🛠 FEATURE

#18 [FEAT] Goal Command Application
  src/main/java/ac/dnd/dodal/application/goal/dto/command/AchieveGoalCommand.java
  src/main/java/ac/dnd/dodal/application/goal/dto/command/CreateGoalCommand.java
  src/main/java/ac/dnd/dodal/application/goal/dto/command/DeleteGoalCommand.java
  src/main/java/ac/dnd/dodal/application/goal/dto/query/.gitkeep
  src/main/java/ac/dnd/dodal/application/goal/repository/GoalCommandRepository.java
  src/main/java/ac/dnd/dodal/application/goal/service/.gitkeep
  src/main/java/ac/dnd/dodal/application/goal/service/GoalCommandService.java
  src/main/java/ac/dnd/dodal/application/goal/usecase/.gitkeep
  src/main/java/ac/dnd/dodal/application/goal/usecase/AchieveGoalUseCase.java
  src/main/java/ac/dnd/dodal/application/goal/usecase/CreateGoalUseCase.java
  src/main/java/ac/dnd/dodal/application/goal/usecase/DeleteGoalUseCase.java
  src/main/java/ac/dnd/dodal/domain/goal/model/Goal.java
  src/test/java/ac/dnd/dodal/application/goal/dto/GoalCommandFixture.java
  src/test/java/ac/dnd/dodal/application/goal/service/GoalCommandServiceTest.java
  src/test/java/ac/dnd/dodal/domain/goal/GoalFixture.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority !! HIGH, Type 🛠 FEATURE

#15 [FEAT] Users 엔티티 추가
  .idea/misc.xml
  src/main/java/ac/dnd/dodal/common/model/BaseEntity.java
  src/main/java/ac/dnd/dodal/domain/user/enums/UserExceptionCode.java
  src/main/java/ac/dnd/dodal/domain/user/enums/UserRole.java
  src/main/java/ac/dnd/dodal/domain/user/exception/UserBadRequestException.java
  src/main/java/ac/dnd/dodal/domain/user/exception/UserNotFoundException.java
  src/main/java/ac/dnd/dodal/domain/user/model/User.java
Labels: PR 🚀 WILL CLOSE, Priority ! MEDIUM, Type 🛠 FEATURE

#16 [FEAT] Spring Security 추가
  build.gradle
  src/main/java/ac/dnd/dodal/application/user/repository/UserRepository.java
  src/main/java/ac/dnd/dodal/common/annotation/UserId.java
  src/main/java/ac/dnd/dodal/common/constant/Constants.java
  src/main/java/ac/dnd/dodal/common/interceptor/UserIdArgumentResolver.java
  src/main/java/ac/dnd/dodal/common/interceptor/UserIdInterceptor.java
  src/main/java/ac/dnd/dodal/config/WebConfig.java
  src/main/java/ac/dnd/dodal/config/security/config/SecurityConfig.java
  src/main/java/ac/dnd/dodal/config/security/enums/SecurityExceptionCode.java
  src/main/java/ac/dnd/dodal/config/security/filter/CustomLogoutFilter.java
  src/main/java/ac/dnd/dodal/config/security/handler/CustomSignOutProcessHandler.java
  src/main/java/ac/dnd/dodal/config/security/handler/CustomSignOutResultHandler.java
  src/main/java/ac/dnd/dodal/config/security/info/CustomUserDetails.java
  src/main/java/ac/dnd/dodal/config/security/service/CustomUserDetailsService.java
  src/main/java/ac/dnd/dodal/domain/user/model/User.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority !! HIGH, Type 🛠 FEATURE

#21 [FEAT] JWT 기능 추가
  .gitignore
  src/main/java/ac/dnd/dodal/common/constant/Constants.java
  src/main/java/ac/dnd/dodal/common/interceptor/UserIdArgumentResolver.java
  src/main/java/ac/dnd/dodal/common/interceptor/UserIdInterceptor.java
  src/main/java/ac/dnd/dodal/core/config/JasyptConfig.java
  src/main/java/ac/dnd/dodal/core/config/WebConfig.java
  src/main/java/ac/dnd/dodal/core/security/JwtAuthEntryPoint.java
  src/main/java/ac/dnd/dodal/core/security/JwtAuthenticationToken.java
  src/main/java/ac/dnd/dodal/core/security/config/SecurityConfig.java
  src/main/java/ac/dnd/dodal/core/security/enums/SecurityExceptionCode.java
  src/main/java/ac/dnd/dodal/core/security/filter/CustomLogoutFilter.java
  src/main/java/ac/dnd/dodal/core/security/filter/JwtAuthenticationFilter.java
  src/main/java/ac/dnd/dodal/core/security/filter/JwtExceptionFilter.java
  src/main/java/ac/dnd/dodal/core/security/handler/CustomSignOutProcessHandler.java
  src/main/java/ac/dnd/dodal/core/security/handler/CustomSignOutResultHandler.java
  src/main/java/ac/dnd/dodal/core/security/handler/JwtAccessDeniedHandler.java
  src/main/java/ac/dnd/dodal/core/security/info/CustomUserDetails.java
  src/main/java/ac/dnd/dodal/core/security/info/JwtUserInfo.java
  src/main/java/ac/dnd/dodal/core/security/provider/JwtAuthenticationProvider.java
  src/main/java/ac/dnd/dodal/core/security/service/CustomUserDetailsService.java
  src/main/java/ac/dnd/dodal/core/security/util/JwtUtil.java
  src/main/java/ac/dnd/dodal/domain/user/enums/UserExceptionCode.java
  src/main/java/ac/dnd/dodal/domain/user/model/User.java
  src/main/java/ac/dnd/dodal/ui/hello/HelloController.java
  src/main/java/ac/dnd/dodal/ui/user/response/JwtTokenDto.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V3__add_user_refresh_token_and_role.sql
  src/test/java/ac/dnd/dodal/application/user/HelloControllerTest.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ! MEDIUM, Type 🛠 FEATURE

#22 [FEAT] Goal Service
  src/main/java/ac/dnd/dodal/application/goal/repository/GoalRepository.java
  src/main/java/ac/dnd/dodal/application/goal/service/GoalCommandService.java
  src/main/java/ac/dnd/dodal/application/goal/service/GoalService.java
  src/test/java/ac/dnd/dodal/application/goal/service/GoalCommandServiceTest.java
  src/test/java/ac/dnd/dodal/application/goal/service/GoalServiceTest.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ! MEDIUM, Type 🛠 FEATURE

#28 [FIX] Remove Config Pacakge
  src/main/java/ac/dnd/dodal/config/WebConfig.java
  src/main/java/ac/dnd/dodal/config/security/config/SecurityConfig.java
  src/main/java/ac/dnd/dodal/config/security/enums/SecurityExceptionCode.java
  src/main/java/ac/dnd/dodal/config/security/filter/CustomLogoutFilter.java
  src/main/java/ac/dnd/dodal/config/security/handler/CustomSignOutProcessHandler.java
  src/main/java/ac/dnd/dodal/config/security/handler/CustomSignOutResultHandler.java
  src/main/java/ac/dnd/dodal/config/security/info/CustomUserDetails.java
  src/main/java/ac/dnd/dodal/config/security/service/CustomUserDetailsService.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ❤️‍🔥 CRITICAL, Type 🪰 BUG FIX

#23 [FEAT] Goal Command API
  src/main/java/ac/dnd/dodal/common/model/BaseEntity.java
  src/main/java/ac/dnd/dodal/domain/goal/model/Goal.java
  src/main/java/ac/dnd/dodal/ui/goal/.gitkeep
  src/main/java/ac/dnd/dodal/ui/goal/GoalController.java
  src/main/java/ac/dnd/dodal/ui/goal/request/CreateGoalRequest.java
  src/main/resources/db/migration/V3__sample_data.sql
  src/test/java/ac/dnd/dodal/acceptance/goal/AchieveGoalAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/goal/CreateGoalAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/goal/steps/GoalSteps.java
  src/test/java/ac/dnd/dodal/ui/goal/fixture/GoalUIFixture.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority !! HIGH, Type 🛠 FEATURE

#30 [REFACTOR] Apply Authorization
  src/main/java/ac/dnd/dodal/domain/user/model/User.java
  src/main/java/ac/dnd/dodal/ui/goal/GoalController.java
  src/main/resources/db/migration/V6__sample_data.sql
  src/test/java/ac/dnd/dodal/AcceptanceTest.java
  src/test/java/ac/dnd/dodal/IntegrationTest.java
  src/test/java/ac/dnd/dodal/acceptance/hello/HelloAcceptanceTest.java
  src/test/java/ac/dnd/dodal/application/user/HelloControllerTest.java
  src/test/java/ac/dnd/dodal/core/security/util/JwtUtilTest.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority !! HIGH, Type 🔨 REFACTOR

#31 [REFACTOR] Remove all unused import statement
  src/main/java/ac/dnd/dodal/common/model/BaseEntity.java
  src/main/java/ac/dnd/dodal/core/security/JwtAuthEntryPoint.java
  src/main/java/ac/dnd/dodal/core/security/config/SecurityConfig.java
  src/main/java/ac/dnd/dodal/core/security/filter/JwtAuthenticationFilter.java
  src/main/java/ac/dnd/dodal/core/security/filter/JwtExceptionFilter.java
  src/main/java/ac/dnd/dodal/core/security/handler/JwtAccessDeniedHandler.java
  src/main/java/ac/dnd/dodal/ui/hello/HelloController.java
  src/main/java/ac/dnd/dodal/ui/user/response/JwtTokenDto.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ? Low, Type 🔨 REFACTOR

#27 [FEAT] OAuth (카카오) 회원 로직
  .idea/google-java-format.xml
  build.gradle
  src/main/java/ac/dnd/dodal/application/user/repository/UserRepository.java
  src/main/java/ac/dnd/dodal/application/user/service/AuthKakaoLoginService.java
  src/main/java/ac/dnd/dodal/application/user/service/AuthService.java
  src/main/java/ac/dnd/dodal/application/user/service/AuthSignUpService.java
  src/main/java/ac/dnd/dodal/application/user/service/UserCommandService.java
  src/main/java/ac/dnd/dodal/application/user/service/UserQueryService.java
  src/main/java/ac/dnd/dodal/application/user/usecase/UserCommandUseCase.java
  src/main/java/ac/dnd/dodal/application/user/usecase/UserQueryUseCase.java
  src/main/java/ac/dnd/dodal/common/constant/Constants.java
  src/main/java/ac/dnd/dodal/common/util/OAuth2Util.java
  src/main/java/ac/dnd/dodal/core/security/util/JwtUtil.java
  src/main/java/ac/dnd/dodal/domain/user/enums/UserExceptionCode.java
  src/main/java/ac/dnd/dodal/ui/auth/AuthController.java
  src/main/java/ac/dnd/dodal/ui/auth/request/OAuthUserInfoRequestDto.java
  src/main/java/ac/dnd/dodal/ui/auth/response/JwtTokenDto.java
  src/main/java/ac/dnd/dodal/ui/auth/response/KakaoUserInfoDto.java
  src/main/java/ac/dnd/dodal/ui/auth/response/UserInfoResponseDto.java
  src/main/java/ac/dnd/dodal/ui/user/.gitkeep
  src/main/resources/db/migration/V4__sample_data.sql
  src/test/java/ac/dnd/dodal/application/user/HelloControllerTest.java
  src/test/java/ac/dnd/dodal/application/user/dto/AuthSignUpFixture.java
  src/test/java/ac/dnd/dodal/application/user/dto/UserCommandFixture.java
  src/test/java/ac/dnd/dodal/application/user/dto/UserQueryFixture.java
  src/test/java/ac/dnd/dodal/application/user/service/AuthRelatedServiceTest.java
  src/test/java/ac/dnd/dodal/application/user/service/UserCommandServiceTest.java
  src/test/java/ac/dnd/dodal/application/user/service/UserQueryServiceTest.java
  src/test/java/ac/dnd/dodal/domain/user/UserFixture.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority !! HIGH, Type 🛠 FEATURE

#29 :sparkles: [FEAT] Apple 로그인 v1 구현
  src/main/java/ac/dnd/dodal/application/user/service/AuthKakaoLoginService.java
  src/main/java/ac/dnd/dodal/application/user/service/AuthLoginService.java
  src/main/java/ac/dnd/dodal/application/user/service/UserQueryService.java
  src/main/java/ac/dnd/dodal/application/user/usecase/UserQueryUseCase.java
  src/main/java/ac/dnd/dodal/common/constant/Constants.java
  src/main/java/ac/dnd/dodal/common/util/OAuth2Util.java
  src/main/java/ac/dnd/dodal/domain/user/enums/UserExceptionCode.java
  src/main/java/ac/dnd/dodal/domain/user/model/User.java
  src/main/java/ac/dnd/dodal/ui/auth/AuthController.java
  src/main/java/ac/dnd/dodal/ui/auth/request/AppleAuthorizationRequestDto.java
  src/main/java/ac/dnd/dodal/ui/auth/request/AppleSignUpRequestDto.java
  src/main/java/ac/dnd/dodal/ui/auth/request/OAuthByAppleUserInfoRequestDto.java
  src/main/java/ac/dnd/dodal/ui/auth/response/AppleIdTokenParsingDto.java
  src/main/java/ac/dnd/dodal/ui/auth/response/AppleUserInfoResponseDto.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V6__sample_data.sql
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ! MEDIUM, Type 🛠 FEATURE

#52 [FIX] Apple Refresh Token 삭제
  src/main/java/ac/dnd/dodal/domain/user/model/User.java
Labels: PR 🚀 WILL CLOSE, Priority ❤️‍🔥 CRITICAL, Type 🪰 BUG FIX

#48 Feat 34/add plan api hj
  src/main/java/ac/dnd/dodal/application/goal/service/GoalPlanCommandService.java
  src/main/java/ac/dnd/dodal/application/goal/usecase/AddPlanUseCase.java
  src/main/java/ac/dnd/dodal/application/goal/usecase/CreatePlanAndHistoryUseCase.java
  src/main/java/ac/dnd/dodal/application/plan/dto/command/AddNewPlanCommand.java
  src/main/java/ac/dnd/dodal/application/plan/dto/command/AddSamePlanCommand.java
  src/main/java/ac/dnd/dodal/application/plan/dto/command/CreatePlanAndHistoryCommand.java
  src/main/java/ac/dnd/dodal/ui/goal/GoalPlanController.java
  src/main/java/ac/dnd/dodal/ui/plan/request/AddNewPlanRequest.java
  src/main/java/ac/dnd/dodal/ui/plan/request/AddSamePlanRequest.java
  src/main/java/ac/dnd/dodal/ui/plan/request/CreatePlanRequest.java
  src/main/resources/db/migration/V6__sample_data.sql
  src/test/java/ac/dnd/dodal/acceptance/goal/AddPlanToGoalAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/goal/steps/AddPlanToGoalSteps.java
  src/test/java/ac/dnd/dodal/ui/plan/fixture/PlanUIFixture.java
Labels: PR 🚀 WILL CLOSE, Priority ❤️‍🔥 CRITICAL, Type 🛠 FEATURE

#49 [FEAT] Add Plan to Goal Application
  src/main/java/ac/dnd/dodal/application/goal/repository/GoalRepository.java
  src/main/java/ac/dnd/dodal/application/goal/service/GoalPlanCommandService.java
  src/main/java/ac/dnd/dodal/application/goal/service/GoalService.java
  src/main/java/ac/dnd/dodal/application/goal/usecase/AddPlanUseCase.java
  src/main/java/ac/dnd/dodal/application/goal/usecase/CreatePlanAndHistoryUseCase.java
  src/main/java/ac/dnd/dodal/application/plan/repository/PlanRepository.java
  src/main/java/ac/dnd/dodal/application/plan/service/PlanCommandService.java
  src/main/java/ac/dnd/dodal/application/plan/service/PlanService.java
  src/main/java/ac/dnd/dodal/application/plan_history/repository/PlanHistoryRepository.java
  src/main/java/ac/dnd/dodal/application/plan_history/service/PlanHistoryService.java
  src/main/java/ac/dnd/dodal/domain/goal/model/Goal.java
  src/main/java/ac/dnd/dodal/domain/plan/model/Plan.java
  src/main/java/ac/dnd/dodal/domain/plan_history/model/PlanHistory.java
  src/main/java/ac/dnd/dodal/ui/goal/GoalPlanController.java
  src/main/resources/db/migration/V6__sample_data.sql
  src/test/java/ac/dnd/dodal/acceptance/goal/AchieveGoalAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/goal/AddPlanToGoalAcceptanceTest.java
  src/test/java/ac/dnd/dodal/application/goal/dto/AddPlanCommandFixture.java
  src/test/java/ac/dnd/dodal/application/plan/service/PlanCommandServiceTest.java
  src/test/java/ac/dnd/dodal/application/plan/service/PlanServiceTest.java
  src/test/java/ac/dnd/dodal/domain/plan/PlanFixture.java
  src/test/java/ac/dnd/dodal/domain/plan_history/PlanHistoryFixture.java
Labels: PR 🚀 WILL CLOSE, Priority ❤️‍🔥 CRITICAL, Type 🛠 FEATURE

#51 [FEAT] Add CompletedDate to Plan
  src/main/java/ac/dnd/dodal/domain/plan/model/Plan.java
  src/main/resources/db/migration/V7__add_completedDate_to_plans.sql
  src/test/java/ac/dnd/dodal/domain/plan/PlanFixture.java
Labels: PR 🚀 WILL CLOSE, Priority !! HIGH, Type 🛠 FEATURE

#54 [FEAT] Complete Plan Application
  src/main/java/ac/dnd/dodal/application/feedback/repository/PlanFeedbackRepository.java
  src/main/java/ac/dnd/dodal/application/feedback/service/PlanFeedbackService.java
  src/main/java/ac/dnd/dodal/application/plan/dto/command/CompletePlanCommand.java
  src/main/java/ac/dnd/dodal/application/plan/service/PlanCommandService.java
  src/main/java/ac/dnd/dodal/domain/plan/model/Plan.java
  src/main/java/ac/dnd/dodal/domain/plan_feedback/model/PlanFeedback.java
  src/main/java/ac/dnd/dodal/domain/plan_feedback/model/PlanFeedbackId.java
  src/main/java/ac/dnd/dodal/ui/feedback/request/CreateFeedbackRequest.java
  src/main/java/ac/dnd/dodal/ui/plan/PlanController.java
  src/main/resources/db/migration/V7__add_completedDate_to_plans.sql
  src/main/resources/db/migration/V8__delete_history_guide.sql
  src/test/java/ac/dnd/dodal/AcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/plan/PlanAcceptanceTest.java
  src/test/java/ac/dnd/dodal/application/plan/dto/CompletePlanCommandFixture.java
  src/test/java/ac/dnd/dodal/application/plan/service/PlanCommandServiceTest.java
  src/test/java/ac/dnd/dodal/domain/feedback/PlanFeedbackFixture.java
Labels: PR 🚀 WILL CLOSE, Priority ❤️‍🔥 CRITICAL, Type 🛠 FEATURE

#55 [REFACTOR] Flyway
  src/main/resources/db/migration/V99__sample_data.sql
  src/test/java/ac/dnd/dodal/flyway/FlywayTest.java
Labels: PR 🚀 WILL CLOSE, Priority ! MEDIUM, Type 🔨 REFACTOR

#57 [FEAT] Get Plans of History
  src/main/java/ac/dnd/dodal/application/feedback/repository/PlanFeedbackRepository.java
  src/main/java/ac/dnd/dodal/application/plan/dto/query/GetPlansOfHistoryQuery.java
  src/main/java/ac/dnd/dodal/application/plan/repository/PlanRepository.java
  src/main/java/ac/dnd/dodal/application/plan/service/PlanQueryService.java
  src/main/java/ac/dnd/dodal/application/plan/usecase/GetPlansOfHistoryUseCase.java
  src/main/java/ac/dnd/dodal/application/plan_history/repository/PlanHistoryRepository.java
  src/main/java/ac/dnd/dodal/common/response/ApiResponse.java
  src/main/java/ac/dnd/dodal/ui/plan/response/PlanElement.java
  src/main/java/ac/dnd/dodal/ui/plan_history/PlanHistoryController.java
  src/main/resources/db/migration/V100__add_completedDate_to_data.sql
  src/test/java/ac/dnd/dodal/acceptance/goal/steps/GoalSteps.java
  src/test/java/ac/dnd/dodal/acceptance/plan/steps/PlanSteps.java
  src/test/java/ac/dnd/dodal/acceptance/plan_history/PlanHistoryAcceptenceTest.java
  src/test/java/ac/dnd/dodal/acceptance/plan_history/steps/GetPlansOfHistoryStep.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority !! HIGH

#56 :sparkles: [FEAT] AccessToken 재발급 API 구현
  src/main/java/ac/dnd/dodal/application/user/service/AuthLoginService.java
  src/main/java/ac/dnd/dodal/application/user/service/AuthService.java
  src/main/java/ac/dnd/dodal/application/user/service/UserQueryService.java
  src/main/java/ac/dnd/dodal/application/user/usecase/UserQueryUseCase.java
  src/main/java/ac/dnd/dodal/ui/auth/AuthController.java
  src/test/java/ac/dnd/dodal/AcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/auth/refreshAccessTokenAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/auth/steps/AuthSteps.java
  src/test/java/ac/dnd/dodal/ui/fixture/UIFixture.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ! MEDIUM, Type 🛠 FEATURE

#63 [REFACTOR] Kakao Login 로직 수정
  src/main/java/ac/dnd/dodal/application/user/repository/UserRepository.java
  src/main/java/ac/dnd/dodal/application/user/service/AuthLoginService.java
  src/main/java/ac/dnd/dodal/application/user/service/AuthSignUpService.java
  src/main/java/ac/dnd/dodal/common/util/OAuth2Util.java
  src/main/java/ac/dnd/dodal/core/security/filter/JwtExceptionFilter.java
  src/main/java/ac/dnd/dodal/core/security/handler/CustomSignOutResultHandler.java
  src/main/java/ac/dnd/dodal/ui/auth/AuthController.java
  src/main/java/ac/dnd/dodal/ui/auth/request/KakaoAuthorizationRequestDto.java
  src/main/java/ac/dnd/dodal/ui/auth/response/KakaoUserInfoDto.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ! MEDIUM, Type 🔨 REFACTOR

#62 :sparkles: [FEAT-53] Onboarding 관련 엔티티 추가
  src/main/java/ac/dnd/dodal/common/util/AnswerContentConverter.java
  src/main/java/ac/dnd/dodal/common/util/QuestionContentConverter.java
  src/main/java/ac/dnd/dodal/domain/onboarding/enums/AnswerContent.java
  src/main/java/ac/dnd/dodal/domain/onboarding/enums/QuestionContent.java
  src/main/java/ac/dnd/dodal/domain/onboarding/model/Answer.java
  src/main/java/ac/dnd/dodal/domain/onboarding/model/AnswerId.java
  src/main/java/ac/dnd/dodal/domain/onboarding/model/Question.java
  src/main/java/ac/dnd/dodal/domain/user/model/UserAnswer.java
  src/main/resources/db/migration/V13__add_table_relating_onboarding.sql
  src/main/resources/db/migration/V14__add_test1_user_onboarding_sample_data.sql
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority !! HIGH, Type 🛠 FEATURE

#65 [FEAT] 온보딩 관련 데이터 조회 기능 구현
  src/main/java/ac/dnd/dodal/application/onboarding/repository/AnswerRepository.java
  src/main/java/ac/dnd/dodal/application/onboarding/repository/QuestionRepository.java
  src/main/java/ac/dnd/dodal/application/onboarding/service/OnBoardingService.java
  src/main/java/ac/dnd/dodal/application/onboarding/usecase/GetQuestionsAndAnswersUseCase.java
  src/main/java/ac/dnd/dodal/ui/onboarding/OnBoardingController.java
  src/main/java/ac/dnd/dodal/ui/onboarding/response/AnswerResponseDto.java
  src/main/java/ac/dnd/dodal/ui/onboarding/response/GetOnBoardingResponseDto.java
  src/test/java/ac/dnd/dodal/acceptance/onboarding/GetOnBoardingDataAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/onboarding/steps/OnBoardingSteps.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority !! HIGH, Type 🛠 FEATURE

#66 [FEAT] UserAnswer Create API 구현
  src/main/java/ac/dnd/dodal/application/onboarding/repository/AnswerRepository.java
  src/main/java/ac/dnd/dodal/application/onboarding/repository/QuestionRepository.java
  src/main/java/ac/dnd/dodal/application/user/repository/UserAnswerRepository.java
  src/main/java/ac/dnd/dodal/application/user/service/UserCommandService.java
  src/main/java/ac/dnd/dodal/application/user/usecase/CreateUserAnswerUseCase.java
  src/main/java/ac/dnd/dodal/domain/onboarding/exception/OnBoardingBadRequestException.java
  src/main/java/ac/dnd/dodal/domain/onboarding/exception/OnBoardingExceptionCode.java
  src/main/java/ac/dnd/dodal/domain/onboarding/exception/OnBoardingNotFoundException.java
  src/main/java/ac/dnd/dodal/ui/user/.gitkeep
  src/main/java/ac/dnd/dodal/ui/user/UserController.java
  src/main/java/ac/dnd/dodal/ui/user/request/CreateUserAnswerRequestDto.java
  src/test/java/ac/dnd/dodal/acceptance/user/CreateUserAnswerAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/user/steps/UserSteps.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority !! HIGH, Type 🛠 FEATURE

#70 [FEAT] 목표별 Daily 계획 조회, Weekly 도달률 조회
  src/main/java/ac/dnd/dodal/application/goal/dto/query/.gitkeep
  src/main/java/ac/dnd/dodal/application/goal/dto/query/GetGoalSuccessRateQuery.java
  src/main/java/ac/dnd/dodal/application/goal/repository/GoalStatisticsRepository.java
  src/main/java/ac/dnd/dodal/application/goal/service/GoalCommandService.java
  src/main/java/ac/dnd/dodal/application/goal/service/GoalStatisticsEventListener.java
  src/main/java/ac/dnd/dodal/application/goal/service/GoalStatisticsService.java
  src/main/java/ac/dnd/dodal/application/goal/usecase/GetGoalSuccessRateUseCase.java
  src/main/java/ac/dnd/dodal/application/plan/dto/query/GetPlansOfGoalQuery.java
  src/main/java/ac/dnd/dodal/application/plan/dto/query/GetWeeklyAchievementRateOfGoalQuery.java
  src/main/java/ac/dnd/dodal/application/plan/repository/PlanRepository.java
  src/main/java/ac/dnd/dodal/application/plan/service/PlanQueryService.java
  src/main/java/ac/dnd/dodal/application/plan/usecase/GetPlansOfGoalByDateUseCase.java
  src/main/java/ac/dnd/dodal/application/plan/usecase/GetWeeklyAchievementRateOfGoalUseCase.java
  src/main/java/ac/dnd/dodal/domain/goal/event/GoalCreatedEvent.java
  src/main/java/ac/dnd/dodal/domain/goal/model/GoalStatistics.java
  src/main/java/ac/dnd/dodal/domain/plan_history/model/HistoryStatistics.java
  src/main/java/ac/dnd/dodal/ui/goal/GoalPlanController.java
  src/main/java/ac/dnd/dodal/ui/goal/GoalStatisticsController.java
  src/main/java/ac/dnd/dodal/ui/goal/response/.gitkeep
  src/main/java/ac/dnd/dodal/ui/goal/response/DailyAchievementRateElement.java
  src/main/java/ac/dnd/dodal/ui/goal/response/GoalStatisticsResponse.java
  src/main/java/ac/dnd/dodal/ui/plan/response/PlanElement.java
  src/main/java/ac/dnd/dodal/ui/plan/response/PlanWithHistoryElement.java
  src/test/java/ac/dnd/dodal/AcceptanceTest.java
  src/test/java/ac/dnd/dodal/IntegrationTest.java
  src/test/java/ac/dnd/dodal/acceptance/goal/GetGoalStatisticsAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/goal/GetPlansOfGoalByDateAcceptacneTest.java
  src/test/java/ac/dnd/dodal/acceptance/goal/steps/GetPlansOfGoalByDateSteps.java
  src/test/java/ac/dnd/dodal/acceptance/goal/steps/GoalStatisticsSteps.java
  src/test/java/ac/dnd/dodal/application/goal/service/GoalCommandServiceTest.java
  src/test/java/ac/dnd/dodal/application/goal/service/GoalStatisticsEventListenerTest.java
  src/test/java/ac/dnd/dodal/application/user/HelloControllerTest.java
  src/test/java/ac/dnd/dodal/config/JasyptConfigTest.java
  src/test/java/ac/dnd/dodal/core/security/util/JwtUtilTest.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ❤️‍🔥 CRITICAL, Type 🛠 FEATURE

#72 [FEAT] 사용자 온보딩 데이터 확인 API 구현
  src/main/java/ac/dnd/dodal/application/user/repository/UserAnswerRepository.java
  src/main/java/ac/dnd/dodal/application/user/service/UserQueryService.java
  src/main/java/ac/dnd/dodal/application/user/usecase/CheckIsDoneUserAnswerUseCase.java
  src/main/java/ac/dnd/dodal/domain/onboarding/exception/OnBoardingExceptionCode.java
  src/main/java/ac/dnd/dodal/ui/user/UserController.java
  src/main/java/ac/dnd/dodal/ui/user/response/GetUserAnswerResponseDto.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ❤️‍🔥 CRITICAL, Type 🛠 FEATURE

#73 [FEAT] Achieved 유무에 따른 User별 목표 리스트 조회
  src/main/java/ac/dnd/dodal/application/goal/repository/GoalRepository.java
  src/main/java/ac/dnd/dodal/application/goal/service/GoalQueryService.java
  src/main/java/ac/dnd/dodal/application/goal/usecase/GetGoalUseCase.java
  src/main/java/ac/dnd/dodal/ui/goal/GoalController.java
  src/main/java/ac/dnd/dodal/ui/goal/response/GoalStatisticsResponse.java
  src/test/java/ac/dnd/dodal/acceptance/goal/GetGoalsAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/goal/steps/GetGoalsSteps.java
Labels: PR 🙇🏻‍♀️ REVIEW REQUEST, Priority ! MEDIUM, Type 🛠 FEATURE

#77 [FEAT #76] 피드백 질문 / 지표 조회 API
  src/main/java/ac/dnd/dodal/application/feedback/repository/DefaultFeedbackIndicatorRepository.java
  src/main/java/ac/dnd/dodal/application/feedback/repository/FeedbackQuestionRepository.java
  src/main/java/ac/dnd/dodal/application/feedback/service/DefaultFeedbackIndicatorService.java
  src/main/java/ac/dnd/dodal/application/feedback/service/FeedbackFacadeService.java
  src/main/java/ac/dnd/dodal/application/feedback/service/FeedbackQuestionService.java
  src/main/java/ac/dnd/dodal/application/feedback/usecase/GetFeedbackQuestionAndIndicatorUseCase.java
  src/main/java/ac/dnd/dodal/application/plan/service/PlanCommandService.java
  src/main/java/ac/dnd/dodal/application/plan_feedback/repository/PlanFeedbackRepository.java
  src/main/java/ac/dnd/dodal/application/plan_feedback/service/PlanFeedbackService.java
  src/main/java/ac/dnd/dodal/common/constant/Constants.java
  src/main/java/ac/dnd/dodal/domain/feedback/enums/FeedbackType.java
  src/main/java/ac/dnd/dodal/domain/feedback/model/DefaultFeedbackIndicator.java
  src/main/java/ac/dnd/dodal/domain/feedback/model/DefaultFeedbackIndicatorId.java
  src/main/java/ac/dnd/dodal/domain/feedback/model/FeedbackQuestion.java
  src/main/java/ac/dnd/dodal/domain/feedback/model/FeedbackQuestionId.java
  src/main/java/ac/dnd/dodal/ui/feedback/FeedbackController.java
  src/main/java/ac/dnd/dodal/ui/feedback/response/FeedbackQuestionAndIndicatorElement.java
  src/main/java/ac/dnd/dodal/ui/feedback/response/FeedbackQuestionAndIndicatorsResponse.java
  src/main/resources/db/migration/V15__change_feedback_question.sql
  src/test/java/ac/dnd/dodal/acceptance/feedback/GetFeedbackQuestionAndIndicatorsAcceptanceTest.java
  src/test/java/ac/dnd/dodal/acceptance/feedback/steps/GetFeedbackQuestionAndIndicatorsStep.java
  src/test/java/ac/dnd/dodal/application/plan/service/PlanCommandServiceTest.java
Labels: PR 🚀 WILL CLOSE, Priority ! MEDIUM, Type 🛠 FEATURE
